import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Navbar from "./components/navbar";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const isClient = typeof window !== "undefined";
    const showNavbar = isClient ? window.location.pathname == "/" : false;

    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
