import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {/* <body className="flex flex-col min-h-screen p-4">
                <div className="flex flex-col lg:flex-row items-center lg:items-start w-full h-full">
                    {/* Logo */}
                {/* <div className="mb-4 lg:mb-0 lg:mr-4 self-center lg:self-start">
                        <Image
                            src="/cog_logo.png"
                            alt="Mon Logo"
                            width={100}
                            height={100}
                        />
                    </div> */}
                {children}
                {/* </div>
            </body> */}
            </body>
        </html>
    );
}
